import matplotlib.pyplot as plt

# Locations and travel times
locations = [
    "Sunway University",
    "Puchong",
    "Petaling Jaya",
    "Subang Jaya",
    "Shah Alam",
    "Klang"
]

travel_times = [18, 24, 20, 19, 15]

# Create figure
fig, ax = plt.subplots(figsize=(8, 12))

# Remove axes
ax.axis("off")

# Vertical positions
y_positions = list(range(len(locations), 0, -1))
x_position = 0.5

# Draw location boxes
for i, (location, y) in enumerate(zip(locations, y_positions)):
    ax.text(
        x_position,
        y,
        location,
        ha="center",
        va="center",
        fontsize=13,
        fontweight="bold",
        bbox=dict(
            boxstyle="round,pad=0.5",
            facecolor="white",
            edgecolor="black",
            linewidth=1.5
        )
    )

    # Draw arrow and travel time to next location
    if i < len(travel_times):
        next_y = y_positions[i + 1]

        ax.annotate(
            "",
            xy=(x_position, next_y + 0.25),
            xytext=(x_position, y - 0.25),
            arrowprops=dict(
                arrowstyle="->",
                linewidth=1.8
            )
        )

        ax.text(
            x_position + 0.12,
            (y + next_y) / 2,
            f"{travel_times[i]} minutes",
            ha="left",
            va="center",
            fontsize=11
        )

# Title
ax.set_title(
    "Final Route Generated by A* Search",
    fontsize=16,
    fontweight="bold",
    pad=20
)

# Set display limits
ax.set_xlim(0, 1)
ax.set_ylim(0.5, len(locations) + 0.7)

plt.tight_layout()

# Save image
plt.savefig(
    "astar_final_route.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()